# StatefulSet例：ステートフルなデータベース（MySQL）
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  labels:
    app: mysql
spec:
  serviceName: mysql-headless  # 関連するHeadless Serviceを指定（必須）
  replicas: 3                  # 作成するPodの数
  selector:
    matchLabels:
      app: mysql               # 管理対象のPodを選択するラベル
  template:                    # Pod定義のテンプレート
    metadata:
      labels:
        app: mysql             # Podに付与するラベル
    spec:
      containers:
      - name: mysql
        image: mysql:8.0       # MySQLコンテナイメージ
        ports:
        - containerPort: 3306  # MySQLの標準ポート
          name: mysql          # ポート名
        env:                   # 環境変数
        - name: MYSQL_ROOT_PASSWORD
          value: "password"    # rootパスワード（本番環境ではSecretを使用）
        - name: MYSQL_DATABASE
          value: "testdb"      # 初期データベース名
        resources:
          requests:            # 最小限必要なリソース
            cpu: 200m          # 200ミリコア
            memory: 256Mi      # 256MiBメモリ
          limits:              # 使用可能な最大リソース
            cpu: 500m          # 500ミリコア
            memory: 512Mi      # 512MiBメモリ
        volumeMounts:
        - name: mysql-data     # PVCの名前（volumeClaimTemplatesで定義）
          mountPath: /var/lib/mysql  # MySQLのデータディレクトリ
        readinessProbe:        # Podがリクエストを受け付け可能かチェック
          exec:
            command:
            - bash
            - -c
            - "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
          initialDelaySeconds: 30  # 最初のチェックまでの待機時間
          periodSeconds: 10        # チェック間隔
        livenessProbe:         # Podが生きているかチェック
          exec:
            command:
            - bash
            - -c
            - "mysql -u root -p$MYSQL_ROOT_PASSWORD -e 'SELECT 1'"
          initialDelaySeconds: 60  # 最初のチェックまでの待機時間
          periodSeconds: 30        # チェック間隔
  volumeClaimTemplates:        # 各Podに自動でPVCを作成
  - metadata:
      name: mysql-data         # PVCのベース名
    spec:
      accessModes: [ "ReadWriteOnce" ]  # 単一Podからの読み書き
      resources:
        requests:
          storage: 1Gi         # 要求するストレージ容量
---
# Headless Service：StatefulSetのPodに固定のDNS名を提供
apiVersion: v1
kind: Service
metadata:
  name: mysql-headless
  labels:
    app: mysql
spec:
  clusterIP: None              # これによりHeadless Serviceになる
  selector:
    app: mysql                 # 対象のPodを選択
  ports:
  - port: 3306                 # Serviceが公開するポート
    targetPort: 3306           # Podのコンテナポート
    name: mysql                # ポート名
